[package]
name = "simd_02_avx_basic"
version = "0.1.0"
authors = ["sydhds"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
